apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nettools.fullname" . }}-evantage-nettools
  labels:
    app: evantage-nettools
  {{- include "nettools.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: evantage-nettools
    {{- include "nettools.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: evantage-nettools
      {{- include "nettools.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args: {{- toYaml .Values.app.args | nindent 8 }}
        command:
        - /bin/bash
        - -c
        - --
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag
          | default .Chart.AppVersion }}
        name: evantage-nettools
        resources: {{- toYaml .Values.app.resources | nindent
          10 }}
      restartPolicy: Always