apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels:
  {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "hello-kubernetes.fullname" . }}
            port:
              number: 80
        path: /
        pathType: Prefix
