apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels:
  {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.helloKubernetes.type }}
  selector:
    app: hello-kubernetes
    {{- include "hello-kubernetes.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.helloKubernetes.ports | toYaml | nindent 2 }}
