apiVersion: v2
name: evantage-nettools
description: A container with network tools on SLE Base Container Image, based on github.com/nicolaka/netshoot
type: application
version: 1.0.4
appVersion: "1.0.0"
maintainers:
  - name: evantage
    email: helm@evantage.nl
annotations:
  catalog.cattle.io/display-name: Evantage Nettools
  catalog.cattle.io/release-name: evantage-nettools