apiVersion: v1
kind: Service
metadata:
  name: {{ include "alien-geeko.fullname" . }}-alien-geeko
  labels:
  {{- include "alien-geeko.labels" . | nindent 4 }}
spec:
  type: {{ .Values.alienGeeko.type }}
  selector:
    app: alien-geeko
    {{- include "alien-geeko.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.alienGeeko.ports | toYaml | nindent 2 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alien-geeko.fullname" . }}-alien-geeko
  labels:
  {{- include "alien-geeko.labels" . | nindent 4 }}
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: alien-geek
    http:
      paths:
      - backend:
          service:
            name: '{{ include "alien-geeko.fullname" . }}-alien-geeko'
            port:
              number: 80
        path: /
        pathType: Prefix
