apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "alien-geeko.fullname" . }}-reader
  labels:
  {{- include "alien-geeko.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "alien-geeko.fullname" . }}-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "alien-geeko.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}