apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- .Values.alienGeeko.ports | toYaml | nindent 2 }}
