# Thanks to https://hub.docker.com/u/olegvorobyov90
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-deny-job
  namespace: darkforce
  labels:
    app: mysql-deny
spec:
  template:
    metadata:
      labels:
        app: mysql-deny
    spec:
      containers:
      - name: mysql-deny
        image: evantage/attack-leap15:0.1
        command: ["/bin/bash"]
        args:
          - -c
          - |
            mariadb -u hacker -psuperdemo -h dvwa-mysql.dvwa.svc.cluster.local
            sleep 3
            mariadb -u root -phacker123 -h dvwa-mysql.dvwa.svc.cluster.local
            sleep 3
            mariadb -u superuser -ppassword123 -h dvwa-mysql.dvwa.svc.cluster.local
            exit 0
      restartPolicy: Never
  backoffLimit: 0

