global:
  imagePullSecrets: []
nginx:
  # Pull the latest nginx image from Docker Hub
  image: nginx:latest
  replicas: 1
  ingress:
    host: "sslip.io"

k6:
  loadTest:
    duration: "60m"
    vus: 10
