kubernetesClusterDomain: cluster.local
led:
  led:
    env:
      mqttPath: channelname
    image:
      repository: wvanderstek/led
      tag: latest
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  replicas: 1
